"""Master rebate-contract templates and formulary-to-template mapping."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set


@dataclass(frozen=True)
class MasterTemplate:
    key: str
    contract_id: str
    contract_name: str
    counterparty: str
    entity_type: str
    folder: str
    rebate_rate_pct: float
    lookback_months: int
    payment_terms_days: int
    notes: str
    stems: Set[str] = field(default_factory=set)
    placeholder: bool = False


def _t(
    key: str,
    contract_id: str,
    contract_name: str,
    counterparty: str,
    folder: str,
    rebate_rate_pct: float,
    lookback_months: int,
    payment_terms_days: int,
    notes: str,
    stems: Set[str],
    *,
    entity_type: str = "pbm",
    placeholder: bool = False,
) -> MasterTemplate:
    return MasterTemplate(
        key=key,
        contract_id=contract_id,
        contract_name=contract_name,
        counterparty=counterparty,
        entity_type=entity_type,
        folder=folder,
        rebate_rate_pct=rebate_rate_pct,
        lookback_months=lookback_months,
        payment_terms_days=payment_terms_days,
        notes=notes,
        stems=stems,
        placeholder=placeholder,
    )


# Permissive demo terms: non_preferred position + all UM allowed.
# Designed to pass every formulary placement except known Module 01 edge cases.

MASTER_TEMPLATES: List[MasterTemplate] = [
    # --- Express Scripts / Evernorth (Ascent) ---
    _t(
        "ascent-national-preferred",
        "ABBV-SYNTHROID-ASCENT-NPF",
        "AbbVie SYNTHROID — Ascent National Preferred Formulary",
        "Express Scripts",
        "ascent",
        32.5,
        12,
        60,
        "Ascent National Preferred Formulary (NPF). Commercial / employer formularies on the national template.",
        {
            "001_TexasAM_ExpressScripts",
            "002_OhioState_ExpressScripts",
            "003_TRS_ActiveCare_ExpressScripts",
            "004_AFSPA_ExpressScripts",
            "037_ExpressScripts_NationalPreferred",
            "070_Wellmark_DrugList",
        },
    ),
    _t(
        "ascent-national-preferred-flex",
        "ABBV-SYNTHROID-ASCENT-NPF-FLEX",
        "AbbVie SYNTHROID — Ascent National Preferred Flex Formulary",
        "Express Scripts",
        "ascent",
        30.0,
        12,
        60,
        "Ascent National Preferred Flex (NPF Flex). No demo formularies in the current 99-PDF set; reserved for flex-template clients.",
        set(),
        placeholder=True,
    ),
    _t(
        "ascent-basic-plus",
        "ABBV-SYNTHROID-ASCENT-BASIC-PLUS",
        "AbbVie SYNTHROID — Ascent Basic / Basic Plus Formulary",
        "Express Scripts",
        "ascent",
        22.0,
        6,
        30,
        "Ascent Basic / Basic Plus template (lower rebate band, tighter tiering).",
        {"060_Highmark_Commercial"},
    ),
    _t(
        "ascent-part-d",
        "ABBV-SYNTHROID-ASCENT-PART-D",
        "AbbVie SYNTHROID — Ascent Part D Formulary",
        "Express Scripts",
        "ascent",
        28.0,
        6,
        30,
        "Ascent Medicare Part D template. Permissive UM terms (ST/MO allowed).",
        {"086_ExpressScriptsMedicare_PDP"},
    ),
    # --- CVS Caremark ---
    _t(
        "caremark-value",
        "ABBV-SYNTHROID-CAREMARK-VALUE",
        "AbbVie SYNTHROID — CVS Caremark Value Formulary",
        "CVS Caremark",
        "caremark",
        18.0,
        6,
        30,
        "CVS Caremark Value template.",
        {"036_CVSCaremark_Value"},
    ),
    _t(
        "caremark-basic-control",
        "ABBV-SYNTHROID-CAREMARK-BASIC-CONTROL",
        "AbbVie SYNTHROID — CVS Caremark Basic Control Formulary",
        "CVS Caremark",
        "caremark",
        24.0,
        12,
        60,
        "CVS Caremark Performance Drug List — Basic Control.",
        {"014_OEFI_CVSCaremark"},
    ),
    _t(
        "caremark-standard-control",
        "ABBV-SYNTHROID-CAREMARK-STANDARD-CONTROL",
        "AbbVie SYNTHROID — CVS Caremark Standard Control + Advanced Specialty",
        "CVS Caremark",
        "caremark",
        27.5,
        12,
        60,
        "CVS Caremark Standard Control with Advanced Control Specialty Formulary.",
        {"013_TeamCare_CVSCaremark", "015_NMPSIA_CVSCaremark"},
    ),
    _t(
        "caremark-preferred-drug-list",
        "ABBV-SYNTHROID-CAREMARK-PREFERRED",
        "AbbVie SYNTHROID — CVS Caremark Preferred / Performance Drug List",
        "CVS Caremark",
        "caremark",
        29.0,
        12,
        60,
        "CVS Caremark Preferred Drug List and client custom performance lists.",
        {"012_Marriott_CVSCaremark", "016_Delaware_CVSCaremark"},
    ),
    # --- Optum Rx ---
    _t(
        "optum-premium-standard",
        "ABBV-SYNTHROID-OPTUM-PREMIUM",
        "AbbVie SYNTHROID — Optum Rx Premium / Premium Standard Formulary",
        "Optum Rx",
        "optum",
        31.0,
        12,
        60,
        "Optum Premium and Premium Standard templates.",
        {
            "005_Michigan_OptumRx",
            "006_Eaton_OptumRx",
            "007_Wespath_OptumRx",
            "009_TrinityHealth_OptumRx",
            "008_MPSERS_OptumRx",
        },
    ),
    _t(
        "optum-select-standard",
        "ABBV-SYNTHROID-OPTUM-SELECT",
        "AbbVie SYNTHROID — Optum Rx Select Standard Formulary",
        "Optum Rx",
        "optum",
        26.0,
        12,
        60,
        "Optum Select Standard template.",
        {"038_OptumRx_SelectStandard"},
    ),
    _t(
        "optum-comprehensive-medicare",
        "ABBV-SYNTHROID-OPTUM-COMPREHENSIVE-PD",
        "AbbVie SYNTHROID — Optum Rx Comprehensive Medicare Formulary",
        "Optum Rx",
        "optum",
        32.5,
        12,
        60,
        "Optum Comprehensive Medicare Part D formulary.",
        {"035_OrangeCounty_OptumRx"},
    ),
    # --- Ascent GPO / allied PBMs ---
    _t(
        "prime-therapeutics",
        "ABBV-SYNTHROID-PRIME-THERAPEUTICS",
        "AbbVie SYNTHROID — Prime Therapeutics (Ascent GPO)",
        "Prime Therapeutics",
        "gpo",
        27.0,
        12,
        60,
        "Prime Therapeutics formularies under the Ascent GPO umbrella.",
        {"011_UMichigan_Prime", "039_PrimeTherapeutics_PrimeChoiceAccord", "072_BCBSAlabama_DrugGuide"},
    ),
    _t(
        "humana-pharmacy-solutions",
        "ABBV-SYNTHROID-HUMANA-PHARMACY",
        "AbbVie SYNTHROID — Humana Pharmacy Solutions (Ascent GPO)",
        "Humana Pharmacy Solutions",
        "gpo",
        30.0,
        6,
        30,
        "Humana employer and PDP formularies.",
        {
            "032_NDPERS_Humana",
            "033_MichiganState_Humana",
            "034_PensionBoardsUCC_Humana",
            "087_HumanaBasicRx_PDP",
            "088_HumanaPremierRx_PDP",
        },
    ),
    _t(
        "envolve-pharmacy-solutions",
        "ABBV-SYNTHROID-ENVOLVE-PHARMACY",
        "AbbVie SYNTHROID — Envolve Pharmacy Solutions (Ascent GPO)",
        "Envolve Pharmacy Solutions",
        "gpo",
        25.0,
        12,
        60,
        "Envolve Pharmacy Solutions template. No formularies in the current demo set.",
        set(),
        placeholder=True,
    ),
    _t(
        "kroger-prescription-plans",
        "ABBV-SYNTHROID-KROGER-RX",
        "AbbVie SYNTHROID — Kroger Prescription Plans (Ascent GPO)",
        "Kroger Prescription Plans",
        "gpo",
        23.5,
        12,
        60,
        "Kroger Prescription Plans template. No formularies in the current demo set.",
        set(),
        placeholder=True,
    ),
    _t(
        "carelonrx",
        "ABBV-SYNTHROID-CARELONRX",
        "AbbVie SYNTHROID — CarelonRx (Ascent GPO)",
        "CarelonRx",
        "gpo",
        26.5,
        12,
        60,
        "CarelonRx template. No formularies in the current demo set.",
        set(),
        placeholder=True,
    ),
    _t(
        "navitus",
        "ABBV-SYNTHROID-NAVITUS",
        "AbbVie SYNTHROID — Navitus Health Solutions",
        "Navitus Health Solutions",
        "gpo",
        24.0,
        12,
        60,
        "Navitus commercial and Medicare PDP formularies.",
        {"010_Wisconsin_Navitus", "041_Navitus_Formularies", "092_NavitusMedicareRx_PDP"},
    ),
    _t(
        "medimpact",
        "ABBV-SYNTHROID-MEDIMPACT",
        "AbbVie SYNTHROID — MedImpact Healthcare Systems",
        "MedImpact",
        "gpo",
        21.0,
        6,
        30,
        "MedImpact Standard, MedPerform Premier, and Select EX templates.",
        {
            "017_MissouriState_MedImpact",
            "018_IbervilleParish_MedImpact",
            "019_Mesa_MedImpact",
            "020_Maryland_MedImpact",
            "040_MedImpact_MedPerformPremier",
            "082_SIHO_MedPerformPremier",
            "083_GlobalHealth_MedImpactSelectEX",
            "084_NMMIP_MedImpactACCESS",
            "085_CommunityCareHealth_MedImpact",
        },
    ),
    _t(
        "silverscript-medicare",
        "ABBV-SYNTHROID-SILVERSCRIPT-MEDICARE",
        "AbbVie SYNTHROID — SilverScript Medicare PDP",
        "SilverScript",
        "gpo",
        29.5,
        6,
        30,
        "SilverScript employer and Medicare PDP formularies (CVS Caremark Medicare).",
        {
            "024_Kansas_SilverScript",
            "025_STRSOhio_SilverScript",
            "026_SCPEBA_SilverScript",
            "027_Louisiana_SilverScript",
            "028_Oklahoma_SilverScriptHigh",
            "029_ClevelandClinic_SilverScript",
            "030_LoudounCounty_SilverScript",
            "031_NYSHIP_SilverScript",
            "089_SilverScriptAetnaMedicareRx_PDP",
        },
    ),
    # --- Other major PBMs / health plans in the demo set ---
    _t(
        "cigna-healthcare",
        "ABBV-SYNTHROID-CIGNA",
        "AbbVie SYNTHROID — Cigna Healthcare PDL",
        "Cigna Healthcare",
        "other",
        26.0,
        12,
        60,
        "Cigna Standard 3-Tier and National Preferred 4-Tier specialty lists.",
        {"021_CGI_Cigna", "022_JPS_Cigna", "050_Cigna_Standard3Tier"},
    ),
    _t(
        "unitedhealthcare",
        "ABBV-SYNTHROID-UHC",
        "AbbVie SYNTHROID — UnitedHealthcare PDL",
        "UnitedHealthcare",
        "other",
        28.0,
        12,
        60,
        "UHC commercial Access 4-Tier and Medicare PDP/MAPD lists.",
        {
            "023_Northwestern_UHC",
            "048_UHC_CommercialPDL",
            "093_UHCGroupMedicareAdvantage_MAPD",
            "094_AARPMedicareRxPreferred_PDP",
        },
    ),
    _t(
        "wellcare-medicare",
        "ABBV-SYNTHROID-WELLCARE",
        "AbbVie SYNTHROID — Wellcare Medicare PDP",
        "Wellcare",
        "other",
        27.0,
        6,
        30,
        "Wellcare Classic and Value Script PDP formularies.",
        {"090_WellcareClassic_PDP", "091_WellcareValueScript_PDP"},
    ),
    _t(
        "kaiser-permanente",
        "ABBV-SYNTHROID-KAISER",
        "AbbVie SYNTHROID — Kaiser Permanente Formulary",
        "Kaiser Permanente",
        "other",
        24.5,
        12,
        60,
        "Kaiser commercial HMO and Medicare Part D formularies.",
        {"051_Kaiser_CACommercialHMO", "095_Kaiser_MedicarePartD"},
        entity_type="health_plan",
    ),
    _t(
        "aetna-standard",
        "ABBV-SYNTHROID-AETNA",
        "AbbVie SYNTHROID — Aetna Standard Plan",
        "Aetna",
        "other",
        25.5,
        12,
        60,
        "Aetna Standard Plan formulary.",
        {"049_Aetna_StandardPlan"},
        entity_type="health_plan",
    ),
    _t(
        "anthem-medicare",
        "ABBV-SYNTHROID-ANTHEM",
        "AbbVie SYNTHROID — Anthem Formularies",
        "Anthem",
        "other",
        27.5,
        12,
        60,
        "Anthem commercial Essential and Medicare Preferred PPO formularies.",
        {"057_Anthem_CT_Essential4Tier", "098_Anthem_MedicarePreferredPPO"},
        entity_type="health_plan",
    ),
    _t(
        "florida-blue",
        "ABBV-SYNTHROID-FLORIDA-BLUE",
        "AbbVie SYNTHROID — Florida Blue Formularies",
        "Florida Blue",
        "other",
        26.5,
        12,
        60,
        "Florida Blue Open Medication Guide and BlueMedicare Comprehensive.",
        {"056_FloridaBlue_OpenMedGuide", "096_FloridaBlue_BlueMedicare"},
        entity_type="health_plan",
    ),
    _t(
        "bcbs-michigan",
        "ABBV-SYNTHROID-BCBS-MI",
        "AbbVie SYNTHROID — Blue Cross Blue Shield of Michigan",
        "Blue Cross Blue Shield of Michigan",
        "other",
        25.0,
        12,
        60,
        "BCBS Michigan Clinical Drug List and Medicare Plus Blue PPO.",
        {"055_BCBSMichigan_ClinicalDrugList", "097_BCBSMichigan_MedicarePlusBluePPO"},
        entity_type="health_plan",
    ),
    _t(
        "bcbs-illinois-hcsc",
        "ABBV-SYNTHROID-BCBS-IL",
        "AbbVie SYNTHROID — Blue Cross Blue Shield of Illinois (HCSC)",
        "Blue Cross Blue Shield of Illinois",
        "other",
        24.0,
        12,
        60,
        "BCBS Illinois multi-plan drug list. [NP] edge case deferred to Module 04.",
        {"071_BCBSIllinois_HCSC_MultiPlan"},
        entity_type="health_plan",
    ),
    _t(
        "regional-blues-and-plans",
        "ABBV-SYNTHROID-REGIONAL-PLANS",
        "AbbVie SYNTHROID — Regional Health Plan Formularies",
        "Regional Health Plans",
        "other",
        23.0,
        12,
        60,
        "Regional Blues, exchange, and independent health-plan formularies in the demo set.",
        {
            "054_HealthNet_CA4Tier",
            "058_HorizonBCBSNJ_Classic",
            "059_BlueShieldCA_Standard",
            "061_Regence_WA_Essential",
            "062_Premera_PreferredB4",
            "063_BCBSTennessee_Preferred",
            "064_BlueCrossNC_Essential5Tier",
            "065_CapitalBlueCross_ExclusiveFull",
            "066_IndependenceBC_SelectDrug",
            "067_EmblemHealth_IFP",
            "068_CareFirst_FEHB",
            "069_Excellus_IndividualDrugList",
            "073_Geisinger_CommercialTraditional",
            "074_HarvardPilgrim_Premium3T",
            "075_Medica_CommercialDrugList",
            "076_HealthPartners_Formulary",
            "077_Providence_FormularyF",
            "078_PriorityHealth_ApprovedDrugList",
            "079_UPMC_Formulary",
            "080_CommunityHealthOptions_Formulary",
            "081_Presbyterian_GroupFormularies",
            "052_Molina_TXMarketplace",
            "053_Ambetter_TX",
            "099_SCAN_MedicarePartD",
            "100_CDPHP_MedicareAdvantagePartD",
        },
        entity_type="health_plan",
    ),
    _t(
        "alternative-pbm",
        "ABBV-SYNTHROID-ALT-PBM",
        "AbbVie SYNTHROID — Alternative PBM Formularies",
        "Alternative PBMs",
        "other",
        20.0,
        6,
        30,
        "Capital Rx, Maxor, SmithRx, ProCare Rx, EmpiRx.",
        {
            "042_CapitalRx_Liberty",
            "043_MaxorPlus_Preferred",
            "045_SmithRx_Essential",
            "046_ProCareRx_National",
            "047_EmpiRx_Open",
        },
    ),
]


STEM_TO_TEMPLATE: Dict[str, str] = {}
for tmpl in MASTER_TEMPLATES:
    for stem in tmpl.stems:
        STEM_TO_TEMPLATE[stem] = tmpl.key


def template_for_stem(stem: str) -> Optional[str]:
    return STEM_TO_TEMPLATE.get(stem)


def all_mapped_stems() -> Set[str]:
    return set(STEM_TO_TEMPLATE.keys())
